namespace StockMarket.Models {
    public class StockDetailSuperficialModel {
        public int sembolid { get; set; }
        public string sembol { get; set; }
        public string tarih { get; set; }
        public decimal alis { get; set; }
        public decimal satis { get; set; }
        public decimal acilis { get; set; }
        public decimal yuksek { get; set; }
        public decimal yukseK1 { get; set; }
        public decimal yukseK2 { get; set; }
        public decimal dusuk { get; set; }
        public decimal dusuK1 { get; set; }
        public decimal dusuK2 { get; set; }
        public decimal kapanis { get; set; }
        public decimal kapaniS1 { get; set; }
        public decimal kapaniS2 { get; set; }
        public decimal hacimlot { get; set; }
        public decimal hacimloT1 { get; set; }
        public decimal hacimloT2 { get; set; }
        public decimal aort { get; set; }
        public decimal aorT1 { get; set; }
        public decimal aorT2 { get; set; }
        public decimal hacimtl { get; set; }
        public decimal hacimtL1 { get; set; }
        public decimal hacimtL2 { get; set; }
        public decimal dunkukapanis { get; set; }
        public decimal oncekikapanis { get; set; }
        public decimal izafikapanis { get; set; }
        public decimal tavan { get; set; }
        public decimal taban { get; set; }
        public decimal yilyuksek { get; set; }
        public decimal yildusuk { get; set; }
        public decimal ayyuksek { get; set; }
        public decimal aydusuk { get; set; }
        public decimal haftayuksek { get; set; }
        public decimal haftadusuk { get; set; }
        public decimal oncekiyilkapanis { get; set; }
        public decimal oncekiaykapanis { get; set; }
        public decimal oncekihaftakapanis { get; set; }
        public decimal yilortalama { get; set; }
        public decimal ayortalama { get; set; }
        public decimal haftaortalama { get; set; }
        public decimal fiyatadimi { get; set; }
        public decimal kaykar { get; set; }
        public decimal sermaye { get; set; }
        public decimal saklamaor { get; set; }
        public decimal netkar { get; set; }
        public string donem { get; set; }
        public decimal fiyatkaz { get; set; }
        public decimal piydeg { get; set; }
        public decimal hacimtldun { get; set; }
        public string aciklama { get; set; }
        public int sektorid { get; set; }
        public decimal yuzdedegisim { get; set; }
        public decimal net { get; set; }
        public decimal hacimyuzdedegisim { get; set; }
        public decimal yuzdedegisimS1 { get; set; }
        public decimal yuzdedegisimS2 { get; set; }
        public decimal ozsermaye { get; set; }
        public decimal beta { get; set; }
        public decimal xU100AG { get; set; }
        public string kapanisfark { get; set; }
    }
}
